export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const DISPLAY_ALERT_DUPLICATE_EMAIL = 'DISPLAY_ALERT_DUPLICATE_EMAIL'
export const DISPLAY_ALERT_EMAIL = 'DISPLAY_ALERT_EMAIL'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_PPV_BEGIN = 'CREATE_PPV_BEGIN'
export const CREATE_PPV_SUCCESS = 'CREATE_PPV_SUCCESS'
export const CREATE_PPV_ERROR = 'CREATE_PPV_ERROR'

export const GET_PPVS_BEGIN = 'GET_PPVS_BEGIN'
export const GET_PPVS_SUCCESS = 'GET_PPVS_SUCCESS'

export const GET_ATTACKER_PPVS_BEGIN = 'GET_ATTACKER_PPVS_BEGIN'
export const GET_ATTACKER_PPVS_SUCCESS = 'GET_ATTACKER_PPVS_SUCCESS'

export const GET_MIDFIELD_PPVS_BEGIN = 'GET_MIDFIELD_PPVS_BEGIN'
export const GET_MIDFIELD_PPVS_SUCCESS = 'GET_MIDFIELD_PPVS_SUCCESS'

export const GET_DEFENSIVE_PPVS_BEGIN = 'GET_DEFENSIVE_PPVS_BEGIN'
export const GET_DEFENSIVE_PPVS_SUCCESS = 'GET_DEFENSIVE_PPVS_SUCCESS'

export const GET_GOALKEEPERS_PPVS_BEGIN = 'GET_GOALKEEPERS_PPVS_BEGIN'
export const GET_GOALKEEPERS_PPVS_SUCCESS = 'GET_GOALKEEPERS_PPVS_SUCCESS'

export const SET_EDIT_PPV = 'SET_EDIT_PPV'
export const RESET_EDIT_PPV = 'RESET_EDIT_PPV'

export const DELETE_PPV_BEGIN = 'DELETE_PPV_BEGIN'

export const EDIT_PPV_BEGIN = 'EDIT_PPV_BEGIN'
export const EDIT_PPV_SUCCESS = 'EDIT_PPV_SUCCESS'
export const EDIT_PPV_ERROR = 'EDIT_PPV_ERROR'
 
export const CLEAR_FILTERS = 'CLEAR_FILTERS'
 


/*  ------------TEAMTRAINING------------ */


export const CREATE_SINGLESMATCH_BEGIN = 'CREATE_SINGLESMATCH_BEGIN'
export const CREATE_SINGLESMATCH_SUCCESS = 'CREATE_SINGLESMATCH_SUCCESS'
export const CREATE_SINGLESMATCH_ERROR = 'CREATE_SINGLESMATCH_ERROR'

export const CREATE_TAGTEAM_BEGIN = 'CREATE_TAGTEAM_BEGIN'
export const CREATE_TAGTEAM_SUCCESS = 'CREATE_TAGTEAM_SUCCESS'
export const CREATE_TAGTEAM_ERROR = 'CREATE_TAGTEAM_ERROR'

export const CREATE_TRIO_BEGIN = 'CREATE_TRIO_BEGIN'
export const CREATE_TRIO_SUCCESS = 'CREATE_TRIO_SUCCESS'
export const CREATE_TRIO_ERROR = 'CREATE_TRIO_ERROR'

export const CREATE_FATALFOUWAY_BEGIN = 'CREATE_FATALFOUWAY_BEGIN'
export const CREATE_FATALFOUWAY_SUCCESS = 'CREATE_FATALFOUWAY_SUCCESS'
export const CREATE_FATALFOUWAY_ERROR = 'CREATE_FATALFOUWAY_ERROR'

export const CREATE_FATALFIVEWAY_BEGIN = 'CREATE_FATALFIVEWAY_BEGIN'
export const CREATE_FATALFIVEWAY_SUCCESS = 'CREATE_FATALFIVEWAY_SUCCESS'
export const CREATE_FATALFIVEWAY_ERROR = 'CREATE_FATALFIVEWAY_ERROR'

export const CREATE_SIXMAN_BEGIN = 'CREATE_SIXMAN_BEGIN'
export const CREATE_SIXMAN_SUCCESS = 'CREATE_SIXMAN_SUCCESS'
export const CREATE_SIXMAN_ERROR = 'CREATE_SIXMAN_ERROR'